# Form implementation generated from reading ui file 'interface-pyqt.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QGraphicsScene, QGraphicsView, QPushButton, QFileDialog
from PyQt6.QtGui import QPixmap, QFont, QIcon
from PyQt6.QtCore import QDir, QSize
import os
from setup_path import absolute_root_path


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):

        QDir.addSearchPath('icons', os.path.join(absolute_root_path, 'interface', 'icons'))
        print('teste', os.path.join(absolute_root_path, 'icons'))
        

        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1100, 700)
        MainWindow.setFixedSize(1100, 700)

        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.scene_img_original = QGraphicsScene()
        self.view_img_original = QGraphicsView(parent=self.centralwidget)
        self.view_img_original.setGeometry(QtCore.QRect(20, 50, 440, 540))  
        self.view_img_original.setScene(self.scene_img_original)
        self.view_img_original.setObjectName("view_img_original")

        self.scene_img_resultante = QGraphicsScene()
        self.view_img_resultante = QGraphicsView(parent=self.centralwidget)
        self.view_img_resultante.setGeometry(QtCore.QRect(470, 50, 440, 540))
        self.view_img_resultante.setScene(self.scene_img_resultante)
        self.view_img_resultante.setObjectName("view_img_resultante")

        self.font_sub = QFont()
        self.font_sub.setFamily("Montserrat")
        self.font_sub.setPointSize(12)

        self.font_title = QFont()
        self.font_title.setFamily("Montserrat")
        self.font_title.setPointSize(18)

        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(160, 610, 260, 50))
        self.label.setObjectName("label")
        self.label.setFont(self.font_sub)

        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(620, 610, 260, 50))
        self.label_2.setObjectName("label_2")
        self.label_2.setFont(self.font_sub)

        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(930, 170, 190, 31))
        self.label_3.setObjectName("label_3")
        self.label_3.setFont(self.font_title)

        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(160, 10, 260, 30))
        self.label_4.setObjectName("label_4")
        self.label_4.setFont(self.font_title)

        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(620, 10, 260, 30))
        self.label_5.setObjectName("label_5")
        self.label_5.setFont(self.font_title)

        icon_reduzir_ruido = QIcon()
        icon_reduzir_ruido.addPixmap(QPixmap("icons:denoising.png"), QIcon.Mode.Normal, QIcon.State.Off)

        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(930, 210, 60, 60))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.setIcon(icon_reduzir_ruido)
        self.pushButton.setIconSize(QSize(self.pushButton.sizeHint().width(), self.pushButton.sizeHint().height()))
        self.pushButton.setToolTip("Reduzir Ruído")

        icon_salvar_imagem = QIcon()
        icon_salvar_imagem.addPixmap(QPixmap("icons:save-result.png"), QIcon.Mode.Normal, QIcon.State.Off)

        self.pushButton_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(1000, 50, 60, 60))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.setIcon(icon_salvar_imagem)
        self.pushButton_2.setIconSize(QSize(self.pushButton_2.sizeHint().width(), self.pushButton_2.sizeHint().height()))
        self.pushButton_2.setToolTip("Salvar Imagem")

        icon_carregar_imagem = QIcon()
        icon_carregar_imagem.addPixmap(QPixmap("icons:load_image.png"), QIcon.Mode.Normal, QIcon.State.Off)

        self.pushButton_3 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(930, 50, 60, 60))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_3.setIcon(icon_carregar_imagem)
        self.pushButton_3.setIconSize(QSize(self.pushButton_3.sizeHint().width(), self.pushButton_3.sizeHint().height()))
        self.pushButton_3.clicked.connect(self.load_image)
        self.pushButton_3.setToolTip("Adicionar Imagem")

        icon_reduzir_borrao = QIcon()
        icon_reduzir_borrao.addPixmap(QPixmap("icons:sharpening.png"), QIcon.Mode.Normal, QIcon.State.Off)

        self.pushButton_4 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(1000, 210, 60, 60))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_4.setIcon(icon_reduzir_borrao)
        self.pushButton_4.setIconSize(QSize(self.pushButton_4.sizeHint().width(), self.pushButton_4.sizeHint().height()))
        self.pushButton_4.setToolTip("Aumentar Nitidez")

        icon_aumentar_resolucao = QIcon()
        icon_aumentar_resolucao.addPixmap(QPixmap("icons:super-resolution.png"), QIcon.Mode.Normal, QIcon.State.Off)

        self.pushButton_5 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(930, 280, 60, 60))
        self.pushButton_5.setIcon(icon_aumentar_resolucao)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_5.sizePolicy().hasHeightForWidth())
        self.pushButton_5.setSizePolicy(sizePolicy)
        self.pushButton_5.setIconSize(QSize(self.pushButton_5.sizeHint().width(), self.pushButton_5.sizeHint().height()))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_5.setToolTip("Aumentar Resolução")

        icon_transferir_estilo = QIcon()
        icon_transferir_estilo.addPixmap(QPixmap("icons:style-transfer.png"), QIcon.Mode.Normal, QIcon.State.Off)

        self.pushButton_6 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(1000, 280, 60, 60))
        self.pushButton_6.setIcon(icon_transferir_estilo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_6.sizePolicy().hasHeightForWidth())
        self.pushButton_6.setIconSize(QSize(self.pushButton_6.sizeHint().width(), self.pushButton_6.sizeHint().height()))
        self.pushButton_6.setSizePolicy(sizePolicy)
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_6.setToolTip("Transferir Estilo")

        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    
    def load_image(self):
        file_name, _ =  QtWidgets.QFileDialog.getOpenFileName(self, 'Selecione uma imagem...', '.', 'Image files (*.jpg *.gif *.png *.jpeg)')
        if file_name:
            pixmap = QPixmap(file_name)
            if not pixmap.isNull():
                self.scene_img_original.clear()
                self.scene_img_original.addPixmap(pixmap)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Free AI Tools"))
        # self.pushButton.setText(_translate("MainWindow", "Reduzir Ruído"))
        self.label.setText(_translate("MainWindow", "Nível de Comprometimento: "))
        self.label_2.setText(_translate("MainWindow", "Nível de Comprometimento: "))
        # self.pushButton_2.setText(_translate("MainWindow", "Salvar Resultado"))
        # self.pushButton_3.setText(_translate("MainWindow", "Carregar Imagem"))
        self.label_3.setText(_translate("MainWindow", "Ferramentas: "))
        # self.pushButton_4.setText(_translate("MainWindow", "Reduzir Borrão"))
        # self.pushButton_5.setText(_translate("MainWindow", "Aumentar Resolução"))
        # self.pushButton_6.setText(_translate("MainWindow", "Transferir Estilo"))
        self.label_4.setText(_translate("MainWindow", "Imagem Original"))
        self.label_5.setText(_translate("MainWindow", "Imagem Resultante"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    app.setStyleSheet("""
    QWidget {
        background-color: #333333;
        color: #ffffff;
    }
    QPushButton {
        background-color: #6F42C1;
        color: #FFFFFF;
        border: none;
        padding: 10px 20px;
        border-radius: 4px;
    }
    QPushButton:hover {
        background-color: #5A32A3;
    }
    QLabel {
        
    }
    QGraphicsView {
        background-color: #696969;
    }
    """)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
